# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Admin/Desktop/Proyecto_final_digital1_PenizzottoM/Proyecto_final_digital1_PenizzottoM.cache/wt [current_project]
set_property parent.project_path C:/Users/Admin/Desktop/Proyecto_final_digital1_PenizzottoM/Proyecto_final_digital1_PenizzottoM.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/Admin/Desktop/Proyecto_final_digital1_PenizzottoM/Proyecto_final_digital1_PenizzottoM.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/Admin/Desktop/Proyecto_final_digital1_PenizzottoM/Proyecto_final_digital1_PenizzottoM.srcs/sources_1/imports/Final_terminado_simOK_videocasiOK_con_adaptarHW/Final_digi1/ffd.vhd
  C:/Users/Admin/Desktop/Proyecto_final_digital1_PenizzottoM/Proyecto_final_digital1_PenizzottoM.srcs/sources_1/imports/Final_terminado_simOK_videocasiOK_con_adaptarHW/Final_digi1/Contador_BCD.vhd
  C:/Users/Admin/Desktop/Proyecto_final_digital1_PenizzottoM/Proyecto_final_digital1_PenizzottoM.srcs/sources_1/imports/Final_terminado_simOK_videocasiOK_con_adaptarHW/Final_digi1/Contador_BCD_completo.vhd
  C:/Users/Admin/Desktop/Proyecto_final_digital1_PenizzottoM/Proyecto_final_digital1_PenizzottoM.srcs/sources_1/imports/Final_terminado_simOK_videocasiOK_con_adaptarHW/Final_digi1/registro_n.vhd
  C:/Users/Admin/Desktop/Proyecto_final_digital1_PenizzottoM/Proyecto_final_digital1_PenizzottoM.srcs/sources_1/imports/Final_terminado_simOK_videocasiOK_con_adaptarHW/work/Contador_aux_pixelX.vhd
  C:/Users/Admin/Desktop/Proyecto_final_digital1_PenizzottoM/Proyecto_final_digital1_PenizzottoM.srcs/sources_1/imports/Final_terminado_simOK_videocasiOK_con_adaptarHW/work/Contador_aux_pixelY.vhd
  C:/Users/Admin/Desktop/Proyecto_final_digital1_PenizzottoM/Proyecto_final_digital1_PenizzottoM.srcs/sources_1/imports/Final_terminado_simOK_videocasiOK_con_adaptarHW/Final_digi1/Contador_binario_330.vhd
  C:/Users/Admin/Desktop/Proyecto_final_digital1_PenizzottoM/Proyecto_final_digital1_PenizzottoM.srcs/sources_1/imports/Final_terminado_simOK_videocasiOK_con_adaptarHW/work/Contador_pixelX_800.vhd
  C:/Users/Admin/Desktop/Proyecto_final_digital1_PenizzottoM/Proyecto_final_digital1_PenizzottoM.srcs/sources_1/imports/Final_terminado_simOK_videocasiOK_con_adaptarHW/work/Contador_pixelY_525.vhd
  C:/Users/Admin/Desktop/Proyecto_final_digital1_PenizzottoM/Proyecto_final_digital1_PenizzottoM.srcs/sources_1/imports/Final_terminado_simOK_videocasiOK_con_adaptarHW/work/fft.vhd
  C:/Users/Admin/Desktop/Proyecto_final_digital1_PenizzottoM/Proyecto_final_digital1_PenizzottoM.srcs/sources_1/imports/Final_terminado_simOK_videocasiOK_con_adaptarHW/work/Generador_senial_sync_horizontal.vhd
  C:/Users/Admin/Desktop/Proyecto_final_digital1_PenizzottoM/Proyecto_final_digital1_PenizzottoM.srcs/sources_1/imports/Final_terminado_simOK_videocasiOK_con_adaptarHW/work/fft_negado.vhd
  C:/Users/Admin/Desktop/Proyecto_final_digital1_PenizzottoM/Proyecto_final_digital1_PenizzottoM.srcs/sources_1/imports/Final_terminado_simOK_videocasiOK_con_adaptarHW/work/Generador_senial_sync_vertical.vhd
  C:/Users/Admin/Desktop/Proyecto_final_digital1_PenizzottoM/Proyecto_final_digital1_PenizzottoM.srcs/sources_1/imports/Final_terminado_simOK_videocasiOK_con_adaptarHW/work/Logica.vhd
  C:/Users/Admin/Desktop/Proyecto_final_digital1_PenizzottoM/Proyecto_final_digital1_PenizzottoM.srcs/sources_1/imports/Final_terminado_simOK_videocasiOK_con_adaptarHW/work/Mux_basico_2a1_width1.vhd
  C:/Users/Admin/Desktop/Proyecto_final_digital1_PenizzottoM/Proyecto_final_digital1_PenizzottoM.srcs/sources_1/imports/Final_terminado_simOK_videocasiOK_con_adaptarHW/work/Mux_2a1_datawitdh4.vhd
  C:/Users/Admin/Desktop/Proyecto_final_digital1_PenizzottoM/Proyecto_final_digital1_PenizzottoM.srcs/sources_1/imports/Final_terminado_simOK_videocasiOK_con_adaptarHW/work/Mux_8a1_datawitdh4.vhd
  C:/Users/Admin/Desktop/Proyecto_final_digital1_PenizzottoM/Proyecto_final_digital1_PenizzottoM.srcs/sources_1/imports/Final_terminado_simOK_videocasiOK_con_adaptarHW/work/ROM.vhd
  C:/Users/Admin/Desktop/Proyecto_final_digital1_PenizzottoM/Proyecto_final_digital1_PenizzottoM.srcs/sources_1/imports/Final_terminado_simOK_videocasiOK_con_adaptarHW/Final_digi1/Registro_completo.vhd
  C:/Users/Admin/Desktop/Proyecto_final_digital1_PenizzottoM/Proyecto_final_digital1_PenizzottoM.srcs/sources_1/imports/Final_terminado_simOK_videocasiOK_con_adaptarHW/work/VGA_controller.vhd
  C:/Users/Admin/Desktop/Proyecto_final_digital1_PenizzottoM/Proyecto_final_digital1_PenizzottoM.srcs/sources_1/imports/Prueba_voltaje_fpga/Voltimetro_dac_pwm.vhd
  C:/Users/Admin/Desktop/Proyecto_final_digital1_PenizzottoM/Proyecto_final_digital1_PenizzottoM.srcs/sources_1/imports/Desktop/ffd_negado.vhd
  C:/Users/Admin/Desktop/Proyecto_final_digital1_PenizzottoM/Proyecto_final_digital1_PenizzottoM.srcs/sources_1/imports/Final_terminado_simOK_videocasiOK_con_adaptarHW/Final_digi1/Voltimetro_hasta_ahora.vhd
  C:/Users/Admin/Desktop/Proyecto_final_digital1_PenizzottoM/Proyecto_final_digital1_PenizzottoM.srcs/sources_1/imports/Final_terminado_simOK_videocasiOK_con_adaptarHW/Top_level+restricciones/Voltimetro_Esquema_Arty_A7-35_top_level.vhd
}
read_ip -quiet C:/Users/Admin/Desktop/Proyecto_final_digital1_PenizzottoM/Proyecto_final_digital1_PenizzottoM.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/Users/Admin/Desktop/Proyecto_final_digital1_PenizzottoM/Proyecto_final_digital1_PenizzottoM.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Admin/Desktop/Proyecto_final_digital1_PenizzottoM/Proyecto_final_digital1_PenizzottoM.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Admin/Desktop/Proyecto_final_digital1_PenizzottoM/Proyecto_final_digital1_PenizzottoM.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Voltimetro_toplevel -part xc7a35tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Voltimetro_toplevel.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Voltimetro_toplevel_utilization_synth.rpt -pb Voltimetro_toplevel_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
